#goal
float32 heading_setpoint
float32 forward_setpoint
float32 rightmove_setpoint
float32 depth_setpoint
---
#result
float32 heading_final
float32 forward_final
float32 rightmove_final
float32 depth_final


---
#feedback
float32 heading_error
float32 forward_error
float32 rightmove_error
float32 depth_error