# TODO: You can change the structure of this message if you need to.
#goal definition
float32 yaw
---
# result definition
float32 elapsed_time
---
# feedback
float32 Desired_yaw
float32 Current_yaw
float32 Error
