; Auto-generated. Do not edit!


(cl:in-package kraken_msgs-msg)


;//! \htmlinclude advancedControllerResult.msg.html

(cl:defclass <advancedControllerResult> (roslisp-msg-protocol:ros-message)
  ((time_taken
    :reader time_taken
    :initarg :time_taken
    :type cl:float
    :initform 0.0))
)

(cl:defclass advancedControllerResult (<advancedControllerResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <advancedControllerResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'advancedControllerResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name kraken_msgs-msg:<advancedControllerResult> is deprecated: use kraken_msgs-msg:advancedControllerResult instead.")))

(cl:ensure-generic-function 'time_taken-val :lambda-list '(m))
(cl:defmethod time_taken-val ((m <advancedControllerResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kraken_msgs-msg:time_taken-val is deprecated.  Use kraken_msgs-msg:time_taken instead.")
  (time_taken m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <advancedControllerResult>) ostream)
  "Serializes a message object of type '<advancedControllerResult>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'time_taken))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <advancedControllerResult>) istream)
  "Deserializes a message object of type '<advancedControllerResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'time_taken) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<advancedControllerResult>)))
  "Returns string type for a message object of type '<advancedControllerResult>"
  "kraken_msgs/advancedControllerResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'advancedControllerResult)))
  "Returns string type for a message object of type 'advancedControllerResult"
  "kraken_msgs/advancedControllerResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<advancedControllerResult>)))
  "Returns md5sum for a message object of type '<advancedControllerResult>"
  "bb94241e261749226844ca094b5ee0a2")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'advancedControllerResult)))
  "Returns md5sum for a message object of type 'advancedControllerResult"
  "bb94241e261749226844ca094b5ee0a2")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<advancedControllerResult>)))
  "Returns full string definition for message of type '<advancedControllerResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%float32 time_taken~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'advancedControllerResult)))
  "Returns full string definition for message of type 'advancedControllerResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%float32 time_taken~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <advancedControllerResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <advancedControllerResult>))
  "Converts a ROS message object to a list"
  (cl:list 'advancedControllerResult
    (cl:cons ':time_taken (time_taken msg))
))
