; Auto-generated. Do not edit!


(cl:in-package kraken_msgs-msg)


;//! \htmlinclude controllerFeedback.msg.html

(cl:defclass <controllerFeedback> (roslisp-msg-protocol:ros-message)
  ((running_time
    :reader running_time
    :initarg :running_time
    :type cl:float
    :initform 0.0))
)

(cl:defclass controllerFeedback (<controllerFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <controllerFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'controllerFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name kraken_msgs-msg:<controllerFeedback> is deprecated: use kraken_msgs-msg:controllerFeedback instead.")))

(cl:ensure-generic-function 'running_time-val :lambda-list '(m))
(cl:defmethod running_time-val ((m <controllerFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kraken_msgs-msg:running_time-val is deprecated.  Use kraken_msgs-msg:running_time instead.")
  (running_time m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <controllerFeedback>) ostream)
  "Serializes a message object of type '<controllerFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'running_time))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <controllerFeedback>) istream)
  "Deserializes a message object of type '<controllerFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'running_time) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<controllerFeedback>)))
  "Returns string type for a message object of type '<controllerFeedback>"
  "kraken_msgs/controllerFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'controllerFeedback)))
  "Returns string type for a message object of type 'controllerFeedback"
  "kraken_msgs/controllerFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<controllerFeedback>)))
  "Returns md5sum for a message object of type '<controllerFeedback>"
  "c2e4e5e2851a3713c120e74e45f192c2")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'controllerFeedback)))
  "Returns md5sum for a message object of type 'controllerFeedback"
  "c2e4e5e2851a3713c120e74e45f192c2")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<controllerFeedback>)))
  "Returns full string definition for message of type '<controllerFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 running_time~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'controllerFeedback)))
  "Returns full string definition for message of type 'controllerFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 running_time~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <controllerFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <controllerFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'controllerFeedback
    (cl:cons ':running_time (running_time msg))
))
