; Auto-generated. Do not edit!


(cl:in-package kraken_msgs-msg)


;//! \htmlinclude orientControllerFeedback.msg.html

(cl:defclass <orientControllerFeedback> (roslisp-msg-protocol:ros-message)
  ((percent_done
    :reader percent_done
    :initarg :percent_done
    :type cl:float
    :initform 0.0))
)

(cl:defclass orientControllerFeedback (<orientControllerFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <orientControllerFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'orientControllerFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name kraken_msgs-msg:<orientControllerFeedback> is deprecated: use kraken_msgs-msg:orientControllerFeedback instead.")))

(cl:ensure-generic-function 'percent_done-val :lambda-list '(m))
(cl:defmethod percent_done-val ((m <orientControllerFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kraken_msgs-msg:percent_done-val is deprecated.  Use kraken_msgs-msg:percent_done instead.")
  (percent_done m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <orientControllerFeedback>) ostream)
  "Serializes a message object of type '<orientControllerFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'percent_done))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <orientControllerFeedback>) istream)
  "Deserializes a message object of type '<orientControllerFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'percent_done) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<orientControllerFeedback>)))
  "Returns string type for a message object of type '<orientControllerFeedback>"
  "kraken_msgs/orientControllerFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'orientControllerFeedback)))
  "Returns string type for a message object of type 'orientControllerFeedback"
  "kraken_msgs/orientControllerFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<orientControllerFeedback>)))
  "Returns md5sum for a message object of type '<orientControllerFeedback>"
  "275881aed49b48fdb4a89a9e2db543b5")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'orientControllerFeedback)))
  "Returns md5sum for a message object of type 'orientControllerFeedback"
  "275881aed49b48fdb4a89a9e2db543b5")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<orientControllerFeedback>)))
  "Returns full string definition for message of type '<orientControllerFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 percent_done~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'orientControllerFeedback)))
  "Returns full string definition for message of type 'orientControllerFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 percent_done~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <orientControllerFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <orientControllerFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'orientControllerFeedback
    (cl:cons ':percent_done (percent_done msg))
))
