set(_CATKIN_CURRENT_PACKAGE "resources")
set(resources_VERSION "1.0.0")
set(resources_MAINTAINER "Prudhvi <prudhvi@teamauv.local>")
set(resources_PACKAGE_FORMAT "1")
set(resources_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(resources_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(resources_BUILDTOOL_DEPENDS "catkin")
set(resources_BUILDTOOL_EXPORT_DEPENDS )
set(resources_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(resources_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(resources_TEST_DEPENDS )
set(resources_DOC_DEPENDS )
set(resources_DEPRECATED "")