/* Auto-generated by genmsg_cpp for file /home/prudhvi/ros_ws/kraken_msgs/msg/controllerResult.msg */
#ifndef KRAKEN_MSGS_MESSAGE_CONTROLLERRESULT_H
#define KRAKEN_MSGS_MESSAGE_CONTROLLERRESULT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace kraken_msgs
{
template <class ContainerAllocator>
struct controllerResult_ {
  typedef controllerResult_<ContainerAllocator> Type;

  controllerResult_()
  : heading_final(0.0)
  , forward_final(0.0)
  , rightmove_final(0.0)
  , depth_final(0.0)
  {
  }

  controllerResult_(const ContainerAllocator& _alloc)
  : heading_final(0.0)
  , forward_final(0.0)
  , rightmove_final(0.0)
  , depth_final(0.0)
  {
  }

  typedef float _heading_final_type;
  float heading_final;

  typedef float _forward_final_type;
  float forward_final;

  typedef float _rightmove_final_type;
  float rightmove_final;

  typedef float _depth_final_type;
  float depth_final;


  typedef boost::shared_ptr< ::kraken_msgs::controllerResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kraken_msgs::controllerResult_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct controllerResult
typedef  ::kraken_msgs::controllerResult_<std::allocator<void> > controllerResult;

typedef boost::shared_ptr< ::kraken_msgs::controllerResult> controllerResultPtr;
typedef boost::shared_ptr< ::kraken_msgs::controllerResult const> controllerResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::kraken_msgs::controllerResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::kraken_msgs::controllerResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace kraken_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::kraken_msgs::controllerResult_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::kraken_msgs::controllerResult_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::kraken_msgs::controllerResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c4ed7083844e87c15cbd06b69847e794";
  }

  static const char* value(const  ::kraken_msgs::controllerResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc4ed7083844e87c1ULL;
  static const uint64_t static_value2 = 0x5cbd06b69847e794ULL;
};

template<class ContainerAllocator>
struct DataType< ::kraken_msgs::controllerResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "kraken_msgs/controllerResult";
  }

  static const char* value(const  ::kraken_msgs::controllerResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::kraken_msgs::controllerResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result\n\
float32 heading_final\n\
float32 forward_final\n\
float32 rightmove_final\n\
float32 depth_final\n\
\n\
\n\
\n\
";
  }

  static const char* value(const  ::kraken_msgs::controllerResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::kraken_msgs::controllerResult_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::kraken_msgs::controllerResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.heading_final);
    stream.next(m.forward_final);
    stream.next(m.rightmove_final);
    stream.next(m.depth_final);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct controllerResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kraken_msgs::controllerResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::kraken_msgs::controllerResult_<ContainerAllocator> & v) 
  {
    s << indent << "heading_final: ";
    Printer<float>::stream(s, indent + "  ", v.heading_final);
    s << indent << "forward_final: ";
    Printer<float>::stream(s, indent + "  ", v.forward_final);
    s << indent << "rightmove_final: ";
    Printer<float>::stream(s, indent + "  ", v.rightmove_final);
    s << indent << "depth_final: ";
    Printer<float>::stream(s, indent + "  ", v.depth_final);
  }
};


} // namespace message_operations
} // namespace ros

#endif // KRAKEN_MSGS_MESSAGE_CONTROLLERRESULT_H

