/* Auto-generated by genmsg_cpp for file /home/prudhvi/ros_ws/kraken_msgs/msg/controllerGoal.msg */
#ifndef KRAKEN_MSGS_MESSAGE_CONTROLLERGOAL_H
#define KRAKEN_MSGS_MESSAGE_CONTROLLERGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace kraken_msgs
{
template <class ContainerAllocator>
struct controllerGoal_ {
  typedef controllerGoal_<ContainerAllocator> Type;

  controllerGoal_()
  : heading_setpoint(0.0)
  , forward_setpoint(0.0)
  , rightmove_setpoint(0.0)
  , depth_setpoint(0.0)
  {
  }

  controllerGoal_(const ContainerAllocator& _alloc)
  : heading_setpoint(0.0)
  , forward_setpoint(0.0)
  , rightmove_setpoint(0.0)
  , depth_setpoint(0.0)
  {
  }

  typedef float _heading_setpoint_type;
  float heading_setpoint;

  typedef float _forward_setpoint_type;
  float forward_setpoint;

  typedef float _rightmove_setpoint_type;
  float rightmove_setpoint;

  typedef float _depth_setpoint_type;
  float depth_setpoint;


  typedef boost::shared_ptr< ::kraken_msgs::controllerGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kraken_msgs::controllerGoal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct controllerGoal
typedef  ::kraken_msgs::controllerGoal_<std::allocator<void> > controllerGoal;

typedef boost::shared_ptr< ::kraken_msgs::controllerGoal> controllerGoalPtr;
typedef boost::shared_ptr< ::kraken_msgs::controllerGoal const> controllerGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::kraken_msgs::controllerGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::kraken_msgs::controllerGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace kraken_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::kraken_msgs::controllerGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::kraken_msgs::controllerGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::kraken_msgs::controllerGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5bf62384fe2248574a658e65808d489d";
  }

  static const char* value(const  ::kraken_msgs::controllerGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5bf62384fe224857ULL;
  static const uint64_t static_value2 = 0x4a658e65808d489dULL;
};

template<class ContainerAllocator>
struct DataType< ::kraken_msgs::controllerGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "kraken_msgs/controllerGoal";
  }

  static const char* value(const  ::kraken_msgs::controllerGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::kraken_msgs::controllerGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal\n\
float32 heading_setpoint\n\
float32 forward_setpoint\n\
float32 rightmove_setpoint\n\
float32 depth_setpoint\n\
\n\
";
  }

  static const char* value(const  ::kraken_msgs::controllerGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::kraken_msgs::controllerGoal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::kraken_msgs::controllerGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.heading_setpoint);
    stream.next(m.forward_setpoint);
    stream.next(m.rightmove_setpoint);
    stream.next(m.depth_setpoint);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct controllerGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kraken_msgs::controllerGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::kraken_msgs::controllerGoal_<ContainerAllocator> & v) 
  {
    s << indent << "heading_setpoint: ";
    Printer<float>::stream(s, indent + "  ", v.heading_setpoint);
    s << indent << "forward_setpoint: ";
    Printer<float>::stream(s, indent + "  ", v.forward_setpoint);
    s << indent << "rightmove_setpoint: ";
    Printer<float>::stream(s, indent + "  ", v.rightmove_setpoint);
    s << indent << "depth_setpoint: ";
    Printer<float>::stream(s, indent + "  ", v.depth_setpoint);
  }
};


} // namespace message_operations
} // namespace ros

#endif // KRAKEN_MSGS_MESSAGE_CONTROLLERGOAL_H

