/* Auto-generated by genmsg_cpp for file /home/prudhvi/ros_ws/kraken_3.0/msgs_stack/kraken_msgs/msg/controllerGoal.msg */
#ifndef KRAKEN_MSGS_MESSAGE_CONTROLLERGOAL_H
#define KRAKEN_MSGS_MESSAGE_CONTROLLERGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace kraken_msgs
{
template <class ContainerAllocator>
struct controllerGoal_ {
  typedef controllerGoal_<ContainerAllocator> Type;

  controllerGoal_()
  : r(0.0)
  , p(0.0)
  , y(0.0)
  , d(0.0)
  {
  }

  controllerGoal_(const ContainerAllocator& _alloc)
  : r(0.0)
  , p(0.0)
  , y(0.0)
  , d(0.0)
  {
  }

  typedef float _r_type;
  float r;

  typedef float _p_type;
  float p;

  typedef float _y_type;
  float y;

  typedef float _d_type;
  float d;


  typedef boost::shared_ptr< ::kraken_msgs::controllerGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kraken_msgs::controllerGoal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct controllerGoal
typedef  ::kraken_msgs::controllerGoal_<std::allocator<void> > controllerGoal;

typedef boost::shared_ptr< ::kraken_msgs::controllerGoal> controllerGoalPtr;
typedef boost::shared_ptr< ::kraken_msgs::controllerGoal const> controllerGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::kraken_msgs::controllerGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::kraken_msgs::controllerGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace kraken_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::kraken_msgs::controllerGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::kraken_msgs::controllerGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::kraken_msgs::controllerGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "210de68057aa57422cc623208f76e5d6";
  }

  static const char* value(const  ::kraken_msgs::controllerGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x210de68057aa5742ULL;
  static const uint64_t static_value2 = 0x2cc623208f76e5d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::kraken_msgs::controllerGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "kraken_msgs/controllerGoal";
  }

  static const char* value(const  ::kraken_msgs::controllerGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::kraken_msgs::controllerGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal\n\
float32 r\n\
float32 p\n\
float32 y\n\
float32 d\n\
\n\
";
  }

  static const char* value(const  ::kraken_msgs::controllerGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::kraken_msgs::controllerGoal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::kraken_msgs::controllerGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.r);
    stream.next(m.p);
    stream.next(m.y);
    stream.next(m.d);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct controllerGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kraken_msgs::controllerGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::kraken_msgs::controllerGoal_<ContainerAllocator> & v) 
  {
    s << indent << "r: ";
    Printer<float>::stream(s, indent + "  ", v.r);
    s << indent << "p: ";
    Printer<float>::stream(s, indent + "  ", v.p);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "d: ";
    Printer<float>::stream(s, indent + "  ", v.d);
  }
};


} // namespace message_operations
} // namespace ros

#endif // KRAKEN_MSGS_MESSAGE_CONTROLLERGOAL_H

