/* Auto-generated by genmsg_cpp for file /home/prudhvi/ros_ws/kraken_3.0/msgs_stack/kraken_msgs/msg/ipControllererror.msg */
#ifndef KRAKEN_MSGS_MESSAGE_IPCONTROLLERERROR_H
#define KRAKEN_MSGS_MESSAGE_IPCONTROLLERERROR_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace kraken_msgs
{
template <class ContainerAllocator>
struct ipControllererror_ {
  typedef ipControllererror_<ContainerAllocator> Type;

  ipControllererror_()
  {
  }

  ipControllererror_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::kraken_msgs::ipControllererror_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kraken_msgs::ipControllererror_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ipControllererror
typedef  ::kraken_msgs::ipControllererror_<std::allocator<void> > ipControllererror;

typedef boost::shared_ptr< ::kraken_msgs::ipControllererror> ipControllererrorPtr;
typedef boost::shared_ptr< ::kraken_msgs::ipControllererror const> ipControllererrorConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::kraken_msgs::ipControllererror_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::kraken_msgs::ipControllererror_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace kraken_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::kraken_msgs::ipControllererror_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::kraken_msgs::ipControllererror_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::kraken_msgs::ipControllererror_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::kraken_msgs::ipControllererror_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::kraken_msgs::ipControllererror_<ContainerAllocator> > {
  static const char* value() 
  {
    return "kraken_msgs/ipControllererror";
  }

  static const char* value(const  ::kraken_msgs::ipControllererror_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::kraken_msgs::ipControllererror_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::kraken_msgs::ipControllererror_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::kraken_msgs::ipControllererror_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::kraken_msgs::ipControllererror_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ipControllererror_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kraken_msgs::ipControllererror_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::kraken_msgs::ipControllererror_<ContainerAllocator> & v) 
  {
  }
};


} // namespace message_operations
} // namespace ros

#endif // KRAKEN_MSGS_MESSAGE_IPCONTROLLERERROR_H

