#!/bin/bash
WS=$ROS_WORKSPACE 
source /opt/ros/hydro/setup.bash
export ROS_WORKSPACE=$WS
export ROS_PACKAGE_PATH=$ROS_WORKSPACE:$ROS_PACKAGE_PATH

roscd kraken_visualization
rosrun uwsim uwsim --configfile kraken/scenes/UWSim_scene.xml
