"""autogenerated by genpy from kraken_msgs/battery.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class battery(genpy.Message):
  _md5sum = "d535a09473d27f72b71883685e5447bb"
  _type = "kraken_msgs/battery"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
float32 cell1
float32 cell2
float32 cell3
float32 cell4
float32 cell5
float32 cell6
float32 vcc
float32 current
float32 energy_consumed
float32 percent_left
 




================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

"""
  __slots__ = ['header','cell1','cell2','cell3','cell4','cell5','cell6','vcc','current','energy_consumed','percent_left']
  _slot_types = ['std_msgs/Header','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,cell1,cell2,cell3,cell4,cell5,cell6,vcc,current,energy_consumed,percent_left

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(battery, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.cell1 is None:
        self.cell1 = 0.
      if self.cell2 is None:
        self.cell2 = 0.
      if self.cell3 is None:
        self.cell3 = 0.
      if self.cell4 is None:
        self.cell4 = 0.
      if self.cell5 is None:
        self.cell5 = 0.
      if self.cell6 is None:
        self.cell6 = 0.
      if self.vcc is None:
        self.vcc = 0.
      if self.current is None:
        self.current = 0.
      if self.energy_consumed is None:
        self.energy_consumed = 0.
      if self.percent_left is None:
        self.percent_left = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.cell1 = 0.
      self.cell2 = 0.
      self.cell3 = 0.
      self.cell4 = 0.
      self.cell5 = 0.
      self.cell6 = 0.
      self.vcc = 0.
      self.current = 0.
      self.energy_consumed = 0.
      self.percent_left = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_10f.pack(_x.cell1, _x.cell2, _x.cell3, _x.cell4, _x.cell5, _x.cell6, _x.vcc, _x.current, _x.energy_consumed, _x.percent_left))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 40
      (_x.cell1, _x.cell2, _x.cell3, _x.cell4, _x.cell5, _x.cell6, _x.vcc, _x.current, _x.energy_consumed, _x.percent_left,) = _struct_10f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_10f.pack(_x.cell1, _x.cell2, _x.cell3, _x.cell4, _x.cell5, _x.cell6, _x.vcc, _x.current, _x.energy_consumed, _x.percent_left))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 40
      (_x.cell1, _x.cell2, _x.cell3, _x.cell4, _x.cell5, _x.cell6, _x.vcc, _x.current, _x.energy_consumed, _x.percent_left,) = _struct_10f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_10f = struct.Struct("<10f")
