##############################Request################################

#kind of vector
#anti-clockwise +ve (0 to 2*pi )
uint32 type #0 for pause the vehicle and 1 to move 
float32 angle

---
#############################Response###############################
uint32 result