##############################Request################################

# 0 sensor control
# 1 ip control
uint32 type

---
#############################Response###############################
bool check
