/* Auto-generated by genmsg_cpp for file /home/prudhvi/ros_ws/kraken_3.0/msgs_stack/ip_msgs/msg/markerFeedback.msg */
#ifndef IP_MSGS_MESSAGE_MARKERFEEDBACK_H
#define IP_MSGS_MESSAGE_MARKERFEEDBACK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace ip_msgs
{
template <class ContainerAllocator>
struct markerFeedback_ {
  typedef markerFeedback_<ContainerAllocator> Type;

  markerFeedback_()
  : errorx(0)
  , errorangle(0.0)
  {
  }

  markerFeedback_(const ContainerAllocator& _alloc)
  : errorx(0)
  , errorangle(0.0)
  {
  }

  typedef int32_t _errorx_type;
  int32_t errorx;

  typedef float _errorangle_type;
  float errorangle;


  typedef boost::shared_ptr< ::ip_msgs::markerFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ip_msgs::markerFeedback_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct markerFeedback
typedef  ::ip_msgs::markerFeedback_<std::allocator<void> > markerFeedback;

typedef boost::shared_ptr< ::ip_msgs::markerFeedback> markerFeedbackPtr;
typedef boost::shared_ptr< ::ip_msgs::markerFeedback const> markerFeedbackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ip_msgs::markerFeedback_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ip_msgs::markerFeedback_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ip_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ip_msgs::markerFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ip_msgs::markerFeedback_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ip_msgs::markerFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ed3078b68744c9114327632d85826408";
  }

  static const char* value(const  ::ip_msgs::markerFeedback_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xed3078b68744c911ULL;
  static const uint64_t static_value2 = 0x4327632d85826408ULL;
};

template<class ContainerAllocator>
struct DataType< ::ip_msgs::markerFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ip_msgs/markerFeedback";
  }

  static const char* value(const  ::ip_msgs::markerFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ip_msgs::markerFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback\n\
int32 errorx\n\
float32 errorangle\n\
\n\
\n\
";
  }

  static const char* value(const  ::ip_msgs::markerFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::ip_msgs::markerFeedback_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ip_msgs::markerFeedback_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.errorx);
    stream.next(m.errorangle);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct markerFeedback_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ip_msgs::markerFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ip_msgs::markerFeedback_<ContainerAllocator> & v) 
  {
    s << indent << "errorx: ";
    Printer<int32_t>::stream(s, indent + "  ", v.errorx);
    s << indent << "errorangle: ";
    Printer<float>::stream(s, indent + "  ", v.errorangle);
  }
};


} // namespace message_operations
} // namespace ros

#endif // IP_MSGS_MESSAGE_MARKERFEEDBACK_H

