/* Auto-generated by genmsg_cpp for file /home/prudhvi/ros_ws/kraken_3.0/msgs_stack/ip_msgs/msg/markerAction.msg */
#ifndef IP_MSGS_MESSAGE_MARKERACTION_H
#define IP_MSGS_MESSAGE_MARKERACTION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ip_msgs/markerActionGoal.h"
#include "ip_msgs/markerActionResult.h"
#include "ip_msgs/markerActionFeedback.h"

namespace ip_msgs
{
template <class ContainerAllocator>
struct markerAction_ {
  typedef markerAction_<ContainerAllocator> Type;

  markerAction_()
  : action_goal()
  , action_result()
  , action_feedback()
  {
  }

  markerAction_(const ContainerAllocator& _alloc)
  : action_goal(_alloc)
  , action_result(_alloc)
  , action_feedback(_alloc)
  {
  }

  typedef  ::ip_msgs::markerActionGoal_<ContainerAllocator>  _action_goal_type;
   ::ip_msgs::markerActionGoal_<ContainerAllocator>  action_goal;

  typedef  ::ip_msgs::markerActionResult_<ContainerAllocator>  _action_result_type;
   ::ip_msgs::markerActionResult_<ContainerAllocator>  action_result;

  typedef  ::ip_msgs::markerActionFeedback_<ContainerAllocator>  _action_feedback_type;
   ::ip_msgs::markerActionFeedback_<ContainerAllocator>  action_feedback;


  typedef boost::shared_ptr< ::ip_msgs::markerAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ip_msgs::markerAction_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct markerAction
typedef  ::ip_msgs::markerAction_<std::allocator<void> > markerAction;

typedef boost::shared_ptr< ::ip_msgs::markerAction> markerActionPtr;
typedef boost::shared_ptr< ::ip_msgs::markerAction const> markerActionConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ip_msgs::markerAction_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ip_msgs::markerAction_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ip_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ip_msgs::markerAction_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ip_msgs::markerAction_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ip_msgs::markerAction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "635f8a394a1189f5961d0395951b7009";
  }

  static const char* value(const  ::ip_msgs::markerAction_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x635f8a394a1189f5ULL;
  static const uint64_t static_value2 = 0x961d0395951b7009ULL;
};

template<class ContainerAllocator>
struct DataType< ::ip_msgs::markerAction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ip_msgs/markerAction";
  }

  static const char* value(const  ::ip_msgs::markerAction_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ip_msgs::markerAction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
markerActionGoal action_goal\n\
markerActionResult action_result\n\
markerActionFeedback action_feedback\n\
\n\
================================================================================\n\
MSG: ip_msgs/markerActionGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
markerGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: ip_msgs/markerGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
int32 order\n\
\n\
================================================================================\n\
MSG: ip_msgs/markerActionResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
markerResult result\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalStatus\n\
GoalID goal_id\n\
uint8 status\n\
uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n\
uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n\
uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n\
                            #   and has since completed its execution (Terminal State)\n\
uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n\
uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n\
                            #    to some failure (Terminal State)\n\
uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n\
                            #    because the goal was unattainable or invalid (Terminal State)\n\
uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n\
                            #    and has not yet completed execution\n\
uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n\
                            #    but the action server has not yet confirmed that the goal is canceled\n\
uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n\
                            #    and was successfully cancelled (Terminal State)\n\
uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n\
                            #    sent over the wire by an action server\n\
\n\
#Allow for the user to associate a string with GoalStatus for debugging\n\
string text\n\
\n\
\n\
================================================================================\n\
MSG: ip_msgs/markerResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
int32[] sequence\n\
\n\
================================================================================\n\
MSG: ip_msgs/markerActionFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
markerFeedback feedback\n\
\n\
================================================================================\n\
MSG: ip_msgs/markerFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback\n\
int32 errorx\n\
float32 errorangle\n\
\n\
\n\
";
  }

  static const char* value(const  ::ip_msgs::markerAction_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ip_msgs::markerAction_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.action_goal);
    stream.next(m.action_result);
    stream.next(m.action_feedback);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct markerAction_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ip_msgs::markerAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ip_msgs::markerAction_<ContainerAllocator> & v) 
  {
    s << indent << "action_goal: ";
s << std::endl;
    Printer< ::ip_msgs::markerActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
s << std::endl;
    Printer< ::ip_msgs::markerActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
s << std::endl;
    Printer< ::ip_msgs::markerActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};


} // namespace message_operations
} // namespace ros

#endif // IP_MSGS_MESSAGE_MARKERACTION_H

