/* Auto-generated by genmsg_cpp for file /home/prudhvi/ros_ws/kraken_3.0/msgs_stack/ip_msgs/msg/markerGoal.msg */
#ifndef IP_MSGS_MESSAGE_MARKERGOAL_H
#define IP_MSGS_MESSAGE_MARKERGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace ip_msgs
{
template <class ContainerAllocator>
struct markerGoal_ {
  typedef markerGoal_<ContainerAllocator> Type;

  markerGoal_()
  : order(0)
  {
  }

  markerGoal_(const ContainerAllocator& _alloc)
  : order(0)
  {
  }

  typedef int32_t _order_type;
  int32_t order;


  typedef boost::shared_ptr< ::ip_msgs::markerGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ip_msgs::markerGoal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct markerGoal
typedef  ::ip_msgs::markerGoal_<std::allocator<void> > markerGoal;

typedef boost::shared_ptr< ::ip_msgs::markerGoal> markerGoalPtr;
typedef boost::shared_ptr< ::ip_msgs::markerGoal const> markerGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ip_msgs::markerGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ip_msgs::markerGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ip_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ip_msgs::markerGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ip_msgs::markerGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ip_msgs::markerGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6889063349a00b249bd1661df429d822";
  }

  static const char* value(const  ::ip_msgs::markerGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x6889063349a00b24ULL;
  static const uint64_t static_value2 = 0x9bd1661df429d822ULL;
};

template<class ContainerAllocator>
struct DataType< ::ip_msgs::markerGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ip_msgs/markerGoal";
  }

  static const char* value(const  ::ip_msgs::markerGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ip_msgs::markerGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
int32 order\n\
\n\
";
  }

  static const char* value(const  ::ip_msgs::markerGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::ip_msgs::markerGoal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ip_msgs::markerGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.order);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct markerGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ip_msgs::markerGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ip_msgs::markerGoal_<ContainerAllocator> & v) 
  {
    s << indent << "order: ";
    Printer<int32_t>::stream(s, indent + "  ", v.order);
  }
};


} // namespace message_operations
} // namespace ros

#endif // IP_MSGS_MESSAGE_MARKERGOAL_H

