DETECT_MARKER=0;
ALLIGN_MARKER=1;
DETECT_BUOY =2
ALLIGN_BUOY =3
DETECT_VGATE =4
ALLIGN_VGATE =5
class Resultheader():
    MARKER_DETECTED =0
    MARKER_ALLIGNED =1
    BUOY_DETECTED= 2
    BUOY_ALLIGNED =3
    VGATE_DETECTED =4
    VGATE_ALLIGNED =5
